name: SQL Server Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-sql:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy SQL script
        run: sqlcmd -S localhost -E -C -i sql/deploy.sql

      - name: Verify tables
        run: sqlcmd -S localhost -E -C -Q "USE DevOpsLab; SELECT name FROM sys.tables;"