name: SQL DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  sql-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SQLite
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3

      - name: Run SQL script
        run: |
          sqlite3 test.db < sql/create_tables.sql

      - name: Verify tables
        run: |
          sqlite3 test.db ".tables"